INSERT INTO LOAN_PRODUCT ( ID, PRODUCT_ID,PRODUCT_NAME) VALUES (100,'hmln', 'Home Loan');
INSERT INTO LOAN_PRODUCT ( ID, PRODUCT_ID,PRODUCT_NAME) VALUES (101,'ccln', 'Credit Card Loan');
INSERT INTO LOAN_PRODUCT ( ID, PRODUCT_ID,PRODUCT_NAME) VALUES (102,'crln', 'Car Loan');
INSERT INTO LOAN_PRODUCT ( ID, PRODUCT_ID,PRODUCT_NAME) VALUES (103,'edln', 'Education Loan');
INSERT INTO LOAN_PRODUCT ( ID, PRODUCT_ID,PRODUCT_NAME) VALUES (104,'agln', 'Agricuture Loan');

INSERT INTO LOAN_INTEREST ( ID, INTEREST_RATE, PRODUCT_ID) VALUES (100,8,'hmln');
INSERT INTO LOAN_INTEREST ( ID, INTEREST_RATE, PRODUCT_ID) VALUES (101,14,'ccln');
INSERT INTO LOAN_INTEREST ( ID, INTEREST_RATE, PRODUCT_ID) VALUES (102,9,'crln');
INSERT INTO LOAN_INTEREST ( ID, INTEREST_RATE, PRODUCT_ID) VALUES (103,12,'edln');
INSERT INTO LOAN_INTEREST ( ID, INTEREST_RATE, PRODUCT_ID) VALUES (104,6,'agln');